apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
secretGenerator:
  -name : mysql-pass
   literal:
  -password=myanam
resources:
  - create-storage.yaml
  - mysql-deployment.yaml
  - wordpress-deployment.yaml